version: "3.1"

services:
  nginx:
    build: .docker/nginx
    container_name: "laravel-docker-nginx"
    depends_on:
      - php-fpm
      - mysql
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    ports:
      - "8000:80"
    restart: always

  php-fpm:
    build: .docker/php-fpm
    container_name: "laravel-docker-php-fpm"
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www
      - ./.docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_DATABASE: laravel-docker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    restart: always

  mysql:
    build: .docker/mysql
    container_name: "laravel-docker-db"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel-docker
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

volumes:
  db-store:
